modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="wanderer_ribbit"
version="1.0.0"
displayName="Wanderer_Ribbit"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.wanderer_ribbit]]
modId="neoforge"
type="required"
versionRange="[21.1.176,)"
ordering="AFTER"
side="BOTH"

[[dependencies.wanderer_ribbit]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"


[[dependencies.wanderer_ribbit]]
modId="geckolib"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"


[[mixins]]
    config="mixins.wanderer_ribbit.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration